import { useMemo, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { BarChart3, Heart, PackageSearch, Sparkles, WalletCards } from 'lucide-react'
import { Button, EmptyState, ProductCard, Stars } from './ui'
import { money, salePrice } from '../lib/utils'
import { scoreProduct } from '../lib/agent'
import type { Product } from '../data/products'

const Chrome = ({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) => <div className="min-h-screen bg-background"><header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link to="/" className="flex items-center gap-2 font-bold"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Sparkles size={16}/></span>Growth<span className="-ml-2 text-primary">Genie</span></Link><nav className="flex items-center gap-1 text-sm font-semibold"><Link className="rounded-md px-3 py-2 hover:bg-accent" to="/products">Products</Link><Link className="rounded-md px-3 py-2 hover:bg-accent" to="/agent">AI Agent</Link><Link className="rounded-md px-3 py-2 hover:bg-accent" to="/cart">Cart</Link></nav></div></header><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><p className="text-sm font-semibold uppercase tracking-[.14em] text-primary">GrowthGenie Intelligence</p><h1 className="mt-2 text-4xl font-bold tracking-tight">{title}</h1><p className="mt-3 max-w-3xl text-muted-foreground">{subtitle}</p>{children}</main></div>

const pick = (catalog: Product[], ids: string[]) => ids.map(id => catalog.find(product => product.id === id)).filter(Boolean) as Product[]

export function ComparePage({ ctx }: { ctx: any }) {
  const [selected, setSelected] = useState<string[]>([])
  const [aiSummary, setAiSummary] = useState('Choose two to four products to receive an evidence-based comparison summary.')
  const [loading, setLoading] = useState(false)
  const products = pick(ctx.catalog, selected)
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 4 ? [...current, id] : current)
  const summarize = async () => {
    if (products.length < 2) { ctx.notify('info', 'Select at least two products', 'You can compare up to four products at once.'); return }
    setLoading(true)
    try {
      const best = [...products].sort((a,b) => (b.aiScore ?? 0) - (a.aiScore ?? 0))[0]
      const prompt = `Summarize a shopping comparison in under 90 words. Products: ${products.map(p => `${p.name}: ₹${salePrice(p.price,p.discount)}, ${p.rating}/5, ${JSON.stringify(p.specs ?? {})}`).join(' | ')}. Recommend ${best.name} if it best balances value and rating.`
      if (window.GENMB_APP_ID) {
        const response = await fetch('/api/ai/completion', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt, appId: window.GENMB_APP_ID, maxTokens: 180 }) })
        const json = await response.json()
        if (!response.ok || !json?.data?.text) throw new Error(json?.message || 'AI summary request failed')
        setAiSummary(json.data.text)
      } else setAiSummary(`Based on price, rating, discount, and feature fit, ${best.name} is the best overall choice. Its ${best.rating}/5 rating and AI value score of ${best.aiScore}/100 make it the most balanced option. Choose another option only if its specific specifications better match your priority.`)
    } catch (err: any) { ctx.notify('error', 'Could not generate AI comparison', err?.message) } finally { setLoading(false) }
  }
  const rows = [['Sale price', p => money(salePrice(p.price,p.discount))], ['Rating', p => `${p.rating}/5`], ['Brand', p => p.brand], ['AI score', p => `${p.aiScore ?? 0}/100`], ['Performance', p => p.specs?.Performance ?? '—'], ['Battery', p => p.specs?.Battery ?? '—'], ['Display', p => p.specs?.Display ?? '—'], ['Storage', p => p.specs?.Storage ?? '—'], ['RAM', p => p.specs?.RAM ?? '—'], ['Camera', p => p.specs?.Camera ?? '—'], ['Warranty', p => p.specs?.Warranty ?? '—']] as Array<[string, (p: Product) => string]>
  return <Chrome title="Compare with confidence" subtitle="Select two to four products. GrowthGenie highlights the trade-offs that matter: value, rating, performance, and key specifications."><div className="mt-8 grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="rounded-lg border bg-card p-4 shadow-sm"><h2 className="font-bold">Choose products ({selected.length}/4)</h2><div className="mt-4 max-h-[520px] space-y-2 overflow-y-auto">{ctx.catalog.map((p: Product) => <label key={p.id} className="flex cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-accent"><input type="checkbox" checked={selected.includes(p.id)} disabled={!selected.includes(p.id) && selected.length >= 4} onChange={() => toggle(p.id)} className="size-4 accent-[var(--primary)]"/><img src={p.image} alt="" className="size-10 rounded object-cover"/><span className="min-w-0 flex-1 truncate text-sm font-semibold">{p.name}</span></label>)}</div></aside><section>{products.length < 2 ? <EmptyState icon={<BarChart3 size={28}/>} title="Choose products to compare" description="Select at least two products from the list to see a full comparison table."/> : <><div className="overflow-x-auto rounded-lg border bg-card shadow-sm"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b bg-muted"><th className="p-4 text-left">Feature</th>{products.map(p => <th key={p.id} className="p-4 text-left"><Link className="hover:text-primary" to={`/product/${p.id}`}>{p.name}</Link></th>)}</tr></thead><tbody>{rows.map(([label, value]) => <tr key={label} className="border-b last:border-0"><td className="bg-muted/40 p-4 font-semibold">{label}</td>{products.map(p => <td key={p.id} className="p-4">{value(p)}</td>)}</tr>)}<tr><td className="bg-muted/40 p-4 font-semibold">Pros</td>{products.map(p=><td key={p.id} className="p-4 text-xs leading-5">{p.pros?.slice(0,2).join(' · ')}</td>)}</tr><tr><td className="bg-muted/40 p-4 font-semibold">Cons</td>{products.map(p=><td key={p.id} className="p-4 text-xs leading-5">{p.cons?.slice(0,2).join(' · ')}</td>)}</tr></tbody></table></div><div className="mt-5 rounded-lg border bg-accent/50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-lg font-bold"><Sparkles size={18} className="text-primary"/> AI comparison summary</h2><Button onClick={summarize} loading={loading} disabled={loading}>Generate summary</Button></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{aiSummary}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{products.map(p => <ProductCard key={p.id} product={p} onAdd={ctx.addToCart} onWish={ctx.toggleWish} wishlisted={ctx.wishlist.includes(p.id)}/>)}</div></>}</section></div></Chrome>
}

export function RecommendationsPage({ ctx }: { ctx: any }) {
  const [budget, setBudget] = useState(65000)
  const preferences = ctx.profile?.preferences?.join(' ') || ''
  const groups = useMemo(() => ({
    'Recommended for you': [...ctx.catalog].sort((a:Product,b:Product) => scoreProduct(b, preferences || 'best value') - scoreProduct(a, preferences || 'best value')).slice(0,4),
    'Best under your budget': ctx.catalog.filter((p:Product) => salePrice(p.price,p.discount) <= budget).sort((a:Product,b:Product) => (b.aiScore ?? 0) - (a.aiScore ?? 0)).slice(0,4),
    'Trending now': [...ctx.catalog].sort((a:Product,b:Product) => b.popularity-a.popularity).slice(0,4)
  }), [ctx.catalog, preferences, budget])
  return <Chrome title="Smart recommendations" subtitle="AI-ranked products shaped by your preferences, shopping activity, wishlist, ratings, and value signals."><div className="mt-7 flex flex-wrap items-center gap-3 rounded-lg border bg-card p-4 shadow-sm"><WalletCards size={19} className="text-primary"/><label className="text-sm font-semibold">Your budget <input className="ml-2 w-32 rounded border bg-background px-2 py-2" type="number" min="500" value={budget} onChange={e=>setBudget(Number(e.target.value)||0)}/></label><span className="text-sm text-muted-foreground">We will prioritize strong fits below {money(budget)}.</span></div>{Object.entries(groups).map(([title, products]) => <section key={title} className="mt-10"><div className="flex items-center gap-2"><PackageSearch size={20} className="text-primary"/><h2 className="text-2xl font-bold">{title}</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.length ? products.map((p:Product)=><ProductCard key={p.id} product={p} onAdd={ctx.addToCart} onWish={ctx.toggleWish} wishlisted={ctx.wishlist.includes(p.id)}/>) : <p className="text-sm text-muted-foreground">No in-stock products match that budget yet.</p>}</div></section>)}</Chrome>
}

export function DashboardPage({ ctx }: { ctx: any }) {
  const wishlistProducts = pick(ctx.catalog, ctx.wishlist)
  const favorite = ctx.catalog.reduce((best: Product | null, p: Product) => !best || p.popularity > best.popularity ? p : best, null)
  const cartValue = ctx.cart.items.reduce((sum:number, item:any) => { const p = ctx.catalog.find((x:Product) => x.id === item.productId); return sum + (p ? salePrice(p.price,p.discount) * item.quantity : 0) }, 0)
  return <Chrome title={`Welcome${ctx.profile?.name ? ` back, ${ctx.profile.name}` : ''}`} subtitle="Your personal GrowthGenie shopping command center: activity, saved products, value insights, and AI picks."><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Cart items" value={String(ctx.cart.items.reduce((sum:number,item:any)=>sum+item.quantity,0))}/><Stat label="Wishlist" value={String(ctx.wishlist.length)}/><Stat label="Current cart value" value={money(cartValue)}/><Stat label="Favorite category" value={favorite?.category ?? 'Explore'}/></div><div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-lg border bg-card p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-bold"><Sparkles size={19} className="text-primary"/> AI shopping insights</h2><div className="mt-4 grid gap-3 text-sm leading-6 text-muted-foreground"><p className="rounded-lg bg-muted p-4">{wishlistProducts.length ? `You have ${wishlistProducts.length} saved products. Compare them before checkout to make sure the feature-to-price balance still works for you.` : 'Save products to your wishlist and GrowthGenie will use them to refine future recommendations.'}</p><p className="rounded-lg bg-muted p-4">{favorite ? `${favorite.category} products are currently leading your discovery feed. In this catalog, the strongest value range is ₹45,000–₹65,000 for performance laptops and premium electronics.` : 'Browse the catalog to unlock category and budget insights.'}</p></div></section><section className="rounded-lg border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Top AI pick</h2>{favorite && <div className="mt-4 flex gap-4"><img src={favorite.image} alt={favorite.name} className="size-20 rounded-lg object-cover"/><div><Link to={`/product/${favorite.id}`} className="font-bold hover:text-primary">{favorite.name}</Link><div className="mt-1"><Stars rating={favorite.rating}/></div><p className="mt-1 font-semibold text-primary">{money(salePrice(favorite.price,favorite.discount))}</p><p className="text-xs text-muted-foreground">AI score {favorite.aiScore}/100</p></div></div>}</section></div></Chrome>
}
function Stat({label,value}:{label:string;value:string}) { return <article className="rounded-lg border bg-card p-5 shadow-sm"><p className="text-sm font-semibold text-muted-foreground">{label}</p><p className="mt-2 truncate text-2xl font-bold">{value}</p></article> }
