import { type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, useEffect, useRef } from 'react'
import { CheckCircle2, CircleAlert, Heart, Loader2, PackageOpen, Star, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { cn, money, salePrice } from '../lib/utils'
import type { Product } from '../data/products'

export function Button({ className, variant = 'primary', loading, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost'; loading?: boolean }) {
  const styles = { primary:'bg-primary text-primary-foreground hover:shadow-md hover:-translate-y-0.5', secondary:'bg-secondary text-secondary-foreground hover:shadow-md hover:-translate-y-0.5', outline:'border bg-card hover:bg-accent hover:text-accent-foreground', destructive:'bg-destructive text-destructive-foreground hover:shadow-md hover:-translate-y-0.5', ghost:'hover:bg-accent hover:text-accent-foreground' }
  return <button {...props} disabled={props.disabled || loading} className={cn('inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition duration-150 active:scale-[.98] focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50', styles[variant], className)}>{loading ? <><Loader2 size={16} className="animate-spin" /><span className="sr-only">Loading</span></> : children}</button>
}
export function Field({ label, error, className, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) {
  const id = props.id ?? `field-${label.toLowerCase().replace(/\W+/g,'-')}`
  return <label className={cn('grid gap-1.5 text-sm font-medium', className)} htmlFor={id}><span>{label}</span><input {...props} id={id} aria-invalid={Boolean(error)} className={cn('min-h-10 rounded-lg border bg-card px-3 text-sm outline-none transition placeholder:text-muted-foreground focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:bg-muted disabled:opacity-50', error && 'border-destructive')} />{error && <span className="text-sm font-normal text-destructive">{error}</span>}</label>
}
export function SelectField({ label, children, className, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; children: ReactNode }) {
  const id = props.id ?? `select-${label.toLowerCase().replace(/\W+/g,'-')}`
  return <label className={cn('grid gap-1.5 text-sm font-medium', className)} htmlFor={id}><span>{label}</span><select {...props} id={id} className="min-h-10 rounded-lg border bg-card px-3 text-sm outline-none focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:bg-muted disabled:opacity-50">{children}</select></label>
}
export function Stars({ rating }: { rating: number }) { return <span className="inline-flex items-center gap-1 text-sm font-semibold"><Star size={15} className="fill-primary text-primary" />{rating.toFixed(1)}</span> }
export function ProductCard({ product, wishlisted, onAdd, onWish }: { product: Product; wishlisted?: boolean; onAdd: (product: Product) => void; onWish: (product: Product) => void }) {
  const price = salePrice(product.price, product.discount)
  return <article className="group relative flex h-full flex-col overflow-hidden rounded-lg border bg-card text-card-foreground shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus-within:ring-2 focus-within:ring-primary">
    <Link to={`/product/${product.id}`} className="block aspect-square overflow-hidden bg-muted"><img data-genmb-img={product.name} src={product.image} alt={product.name} width="800" height="800" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]" onError={(event) => { event.currentTarget.src = `https://picsum.photos/seed/${product.id}-fallback/800/800` }} /></Link>
    <button onClick={() => onWish(product)} aria-label={wishlisted ? `Remove ${product.name} from wishlist` : `Add ${product.name} to wishlist`} className={cn('absolute right-3 top-3 rounded-full bg-card/95 p-2 shadow-sm transition hover:bg-accent focus-visible:ring-2 focus-visible:ring-ring', wishlisted && 'text-destructive')}><Heart size={17} className={wishlisted ? 'fill-current' : ''} /></button>
    <div className="flex flex-1 flex-col gap-3 p-4"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">{product.brand} · {product.category}</p><Link to={`/product/${product.id}`} className="mt-1 block font-semibold leading-snug hover:text-primary">{product.name}</Link></div><div className="mt-auto flex items-end justify-between gap-2"><div><p className="text-lg font-bold">{money(price)} {product.discount > 0 && <span className="ml-1 text-xs font-medium text-muted-foreground line-through">{money(product.price)}</span>}</p><p className="mt-1 text-muted-foreground"><Stars rating={product.rating} /> <span className="ml-1 text-xs">({product.reviewCount})</span></p></div><Button className="shrink-0 px-3" onClick={() => onAdd(product)} disabled={product.stock === 0}>{product.stock ? 'Add' : 'Sold out'}</Button></div></div>
  </article>
}
export function EmptyState({ icon, title, description, action }: { icon?: ReactNode; title: string; description: string; action?: ReactNode }) { return <div className="flex min-h-64 flex-col items-center justify-center rounded-lg border border-dashed bg-card p-8 text-center"><div className="mb-4 rounded-full bg-muted p-4 text-muted-foreground">{icon ?? <PackageOpen size={28} />}</div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>{action && <div className="mt-5">{action}</div>}</div> }
export type Toast = { id: string; type: 'success' | 'error' | 'info'; title: string; description?: string }
export function ToastViewport({ toasts, onDismiss }: { toasts: Toast[]; onDismiss: (id: string) => void }) { return <div aria-live="polite" className="fixed bottom-5 right-5 z-50 grid w-[min(92vw,380px)] gap-3">{toasts.map((toast) => <div key={toast.id} className="fade-in flex gap-3 rounded-lg border bg-popover p-4 text-popover-foreground shadow-md"><div className={toast.type === 'error' ? 'text-destructive' : toast.type === 'success' ? 'text-primary' : 'text-muted-foreground'}>{toast.type === 'error' ? <CircleAlert size={20} /> : <CheckCircle2 size={20} />}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{toast.title}</p>{toast.description && <p className="mt-0.5 text-sm text-muted-foreground">{toast.description}</p>}</div><button aria-label="Dismiss notification" onClick={() => onDismiss(toast.id)} className="rounded p-1 text-muted-foreground hover:bg-accent"><X size={16} /></button></div>)}</div> }
export function Modal({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { const closeRef = useRef<HTMLButtonElement>(null); const dialogRef = useRef<HTMLElement>(null); useEffect(() => { if (!open) return; const previous = document.activeElement as HTMLElement | null; closeRef.current?.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'Tab' && dialogRef.current) { const focusable = Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled])')); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } } }; document.addEventListener('keydown', keydown); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', keydown); document.body.style.overflow = ''; previous?.focus() } }, [open, onClose]); if (!open) return null; return <div className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/25 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="modal-title" className="fade-in max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-lg border bg-popover p-6 text-popover-foreground shadow-md"><div className="mb-5 flex items-center justify-between gap-4"><h2 id="modal-title" className="text-xl font-bold">{title}</h2><button ref={closeRef} onClick={onClose} aria-label="Close dialog" className="rounded p-2 hover:bg-accent"><X size={18} /></button></div>{children}</section></div> }
